### ISSUE TITLE
Permutation and Combination

### ISSUE THREAD

**Issue by chinmaypant21** [chinmaypant21/Discrete_Structures#6]
Write a Program to calculate Permutation and Combination for an input value n and r using recursive formula of nCr and nPr .

**Comment by underscoremissa** [comment]
Hello, I would like to work on this in Cpp.

**Comment by underscoremissa** [comment]
> @underscoremissa it would be great if you can do this as Q11 as other programs are also scheduled between this (according to guidelines by Discrete Structures Paper Practicals).

Renamed to Q11. Thankyou.

**Comment by ayushgupta0110** [comment]
Pull request raised #9

**Comment by chinmaypant21** [comment]
@ayushgupta0110 #9 Fixed #6
